### ISSUE TITLE
Pocket Coursica Content 1

### ISSUE THREAD

**Issue by C-Air-Uh** [mozilla/moz-corsica#145]
Hello,

I'd love to add the following tweets to the Coursica for Pocket:

https://twitter.com/KarenBakerTX/status/1085918379997888513
https://twitter.com/Fexican12/status/1085656380076306432
https://twitter.com/poppyashwright/status/1085628896479977474
https://twitter.com/TheTechChef/status/1082424461976948737
https://twitter.com/magicTuscan/status/1084913380987678720
https://twitter.com/TmoneyTalks/status/1084695389163405312

**Comment by mythmon** [comment]
Hi @C-Air-Uh,

Corsica doesn't support directly adding Tweets, since they are not formatted for display on the TV. You'll need to format these in some way that is formatted for the screen.

I believe Asa Dotzler manages this by maintaining a Google Slides document with one slide per tweet. Corsica can be configured to display that Google Slides document. Additionally, you can update the document in the future if the tweets change. Would that work for you?

**Comment by emceeaich** [comment]
Sent @C-Air-Uh the link to Asa's presentation to copy and get the link of the copy.

**Comment by lonnen** [comment]
I believe this has resolved itself?

**Comment by lonnen** [comment]
edit: did not intent to close. Errant click. Suggest closing, though
