### ISSUE TITLE
Andrew's Corsica

### ISSUE THREAD

**Issue by andrewkrug** [mozilla/moz-corsica#168]
the name of the screen: wiz-kid
where it's physically located: andrew's house
what content should be on it: can I have all the content? I especially like PDX ambient.  Don't mind seeing what's for lunch either in all locations.
any other special requests: nope

**Comment by mythmon** [comment]
This kind of configuration happens locally on the client, or remotely via runtime commands. The easiest thing you can do is to use the [Corsica Repl](https://github.com/potch/corsica-repl) to issue the following commands:

* First set up the repl: `repl server https://corsica.mozilla.io/`
* Choose your screen from the drop down in the bottom right
* Execute this command for each tag you'd like to subscribe to: `admin type=subscribe tag=$TAG`

To see a list of available tags, you can either consult [`state.json`](https://github.com/mozilla/moz-corsica/blob/master/state.json) in this repository, or look at the live list, which includes current subscriptions, here: https://corsica.mozilla.io/tags

I'm going to close this issue, since no work needs done in this repository. I'm happy to keep helping if you have any trouble though.
